baseURL = "https://yongjie.codes"
languageCode = "en"
DefaultContentLanguage = "en"
title = "A Random Programmer"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-144641266-1"

[params]
title = "I'm Yong Jie"
author = "Yong Jie"
description = "You can call me YJ. I write code, write about writing code (here), and sometimes speak about writing code. I enjoy coding in general, and have written (poor) programs from Flash games to Office Add-ins, browser extensions, web applications, desktop applications, data-analytics tools..."
profilePicture = "img/avatar.jpg"
keywords = ""
favicon = "img/favicons/"
customCss = ["css/custom.css"]
customJs = []
mainSections = ["posts", "guides"] # This determines, among other things, what is on the home page.

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/khooyongjie/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/yongjieyongjie"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://gitlab.com/yongjieyongjie"

# [[params.socialIcons]]
# icon = "fa-instagram"
# title = "instagram"
# url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:khooyongjie@gmx.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

#  [[menu.main]]
#  name = "About"
#  weight = 200
#  identifier = "about"
#  url = "/about/"

  [[menu.main]]
  name = "Guides"
  weight = 250
  identifier = "guides"
  url = "/guides/"

  [[menu.main]]
  name = "Posts"
  weight = 300
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Reading Logs"
  weight = 350
  identifier = "reading-logs"
  url = "/reading-logs/"

  [[menu.main]]
  name = "Portfolio (badly outdated)"
  weight = 400
  identifier = "Portfolio"
  url = "/portfolio/"

  [[menu.main]]
  name = "Kafka Surveyor (NEW!)"
  weight = 450
  identifier = "Kafka-Surveyor"
  url = "/kafka-surveyor/"
