baseURL = "https://yongjie.codes/"
languageCode = "en-us"
title = "Yong Jie | Codes"
theme = "pulp"
    
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
googleAnalytics = "UA-144641266-1"

[taxonomies]
  series = "series"

[params]
    author = "Yong Jie"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        Programmer | Ex-Lawyer | .*
    """
    publicationYear = "2019"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    identifier = "blog"
    # name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-pen fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "reading logs"
    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "/reading-logs/"
    weight = 10

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/yongjieyongjie"
    weight = 30

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:khooyongjie@gmx.com"
    weight = 40

[[menu.main]]
    identifier = "resume"
    # name = "resume"
    pre = "<i class='fa fa-file-code fa-lg'></i>"
    url = "https://bit.ly/yongjie_resume"
    weight = 40
